import { StyleSheet } from "react-native";
import { textInputDefaultSize, scale } from "../../Utils/constants";
const styles = StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: "center",
        backgroundColor: "#152259",
    },
    waitingCircle: {
        position: "absolute",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        justifyContent: "center",
        alignItems: "center",
        zIndex: 1,
    },
    scrollview: {
        flex: 1,
        backgroundColor: "white",
        borderRadius: 20,
        paddingTop: 50,
    },
    form: {
        flex: 0.8,
        backgroundColor: "white",
        borderRadius: 20,
        paddingTop: 50,
    },
    head: {
        alignItems: "center",
        justifyContent: "center",
        alignSelf: "center",
        marginBottom: 55,
    },
    backContainer: {
        position: "absolute",
        top: 30,
        left: 20,
        paddingRight: 5,
        paddingBottom: 5,
    },
    backBtn: {
        width: 25,
        height: 25,
    },
    title: {
        fontSize: 45 * scale,
        fontFamily: "Inter",
        fontStyle: "normal",
        color: "#152259",
        opacity: 1,
        textAlign: "center",
        textAlignVertical: "center",
    },
    subtitle: {
        fontFamily: "Be Vietnam italic",
        fontSize: 15 * scale,
        height: 20,
        alignSelf: "flex-end",
    },
    body: {
        flex: 0.5,
        alignItems: "center",
        justifyContent: "flex-start",
        paddingHorizontal: 18,
        gap: 14,
    },
    textInput: {
        alignItems: "center",
        flexDirection: "row",
    },
    formikInput: {
        flexDirection: "column",
        alignItems: "flex-start",
    },
    input: {
        height: 50,
        flexBasis: 1,
        flexGrow: 1,
        borderWidth: 1,
        borderColor: "#43BDD4",
        borderRadius: 10,
        padding: 10,
        marginLeft: 10,
        fontSize: textInputDefaultSize * scale,
        color: "#5C5D60",
        opacity: 1,
    },
    error: {
        color: "red",
        fontWeight: "bold",
        marginTop: 5,
        marginLeft: 125,
    },
    icon: {
        position: "absolute",
        right: 7,
        padding: 5,
    },
    btnRegister: {
        marginTop: 20,
        borderRadius: 5,
        backgroundColor: "#152259",
        width: 246,
        height: 50,
        alignItems: "center",
        justifyContent: "center",
        alignSelf: "center",
    },
    txtRegister: {
        color: "white",
        fontSize: 14 * scale,
        fontWeight: "bold",
    },
    btnRegisterWithGoogle: {
        borderRadius: 5,
        backgroundColor: "white",
        borderWidth: 1,
        borderColor: "lightgray",
        width: 246,
        height: 50,
        alignItems: "center",
        justifyContent: "center",
        flexDirection: "row",
        gap: 10,
    },
    txtRegisterWithGoogle: {
        color: "black",
        fontSize: 14 * scale,
        fontWeight: "bold",
    },
    foot: {
        position: "absolute",
        bottom: 40,
        width: "100%",
    },
    footContent: {
        alignItems: "center",
    },
});

export default styles;
